version: "3.8"

services:
  db_tests:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-tests-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ltree_tests
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 25432:5432

volumes:
  postgres-tests-data: